app:
  security:
    jwk-set-json-file: ${APP_SECURITY_JWK_SET_JSON_FILE:.local/jwk-set.json}
  mail:
    delivery-mode: log

logging:
  level:
    br.com.stickerswap.identity.service.AccountEmailServiceImpl: DEBUG
