server:
  forward-headers-strategy: framework

spring:
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  profiles:
    active: local

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,httpexchanges,prometheus
  endpoint:
    health:
      show-details: always

app:
  database:
    driver-class-name: org.postgresql.Driver
    pool-name: StickerSwapPool
    maximum-pool-size: 20
    minimum-idle: 5
    connection-timeout: 30s
    idle-timeout: 10m
    max-lifetime: 30m
    keep-alive-time: 5m
  oauth:
    web-client:
      client-id: sticker-swap-web
  cep:
    api-base-url: ${CEP_API_BASE_URL:https://brasilapi.com.br}
    connect-timeout: ${CEP_API_CONNECT_TIMEOUT:3s}
    read-timeout: ${CEP_API_READ_TIMEOUT:3s}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId:-}] [%X{spanId:-}] [%X{userId:-anon}] %logger{36} - %msg%n"
  level:
    br.com.stickerswap: INFO
    org:
      springframework.security: WARN
